import axios from 'axios';

type acronym = {
	slug: string;
	acronym: string;
	full_form: string;
	description: string;
	markdown: string;
	related: Array<acronym['slug']>;
};

const acronyms: acronym[] = [
	{
		slug: 'advanced-package-tool',
		acronym: 'APT',
		full_form: 'Advanced Package Tool',
		description:
			'APT is a package management system used by Debian and its derivatives, such as Ubuntu. It simplifies the process of installing, upgrading, and removing software packages.',
		markdown:
			'### Key Features:\n\n* Simplifies package management\n* Handles dependencies automatically\n* Supports various package sources (repositories)\n\n### Usage:\n\n* `apt-get`: Command-line tool for package management\n* `apt-cache`: Tool for searching and displaying package information\n* `apt-key`: Tool for managing package keys\n\n',
		related: ['advanced-persistent-threat']
	},
	{
		slug: 'advanced-persistent-threat',
		acronym: 'APT',
		full_form: 'Advanced Persistent Threat',
		description:
			'APT refers to a prolonged and targeted cyberattack in which an intruder gains access to a network and remains undetected for an extended period. APTs are often associated with state-sponsored actors or organized crime groups.',
		markdown:
			'### Advanced Persistent Threat (APT)\n#### Definition\nAdvanced Persistent Threat (APT) refers to a prolonged and targeted cyberattack in which an intruder gains access to a network and remains undetected for an extended period.\n\n#### Characteristics\n* Prolonged and targeted cyberattack\n* Intruder gains access to a network and remains undetected for an extended period\n* Often associated with state-sponsored actors or organized crime groups\n\n',
		related: ['advanced-package-tool']
	},
	{
		slug: 'cloud-native-application-protection-platform',
		acronym: 'CNAPP',
		full_form: 'Cloud-Native Application Protection Platform',
		description:
			'CNAPP is a security solution designed to protect cloud-native applications throughout their lifecycle. It integrates various security tools and practices to ensure the security of applications deployed in cloud environments.',
		markdown:
			'## Cloud-Native Application Protection Platform (CNAPP)\n\nThe Cloud-Native Application Protection Platform (CNAPP) is a security solution designed to protect cloud-native applications throughout their lifecycle. It integrates various security tools and practices to ensure the security of applications deployed in cloud environments.\n\n### Key Features:\n\n* Comprehensive security for cloud-native applications\n* Integration of various security tools and practices\n* Continuous monitoring and assessment of application security\n\n### Usage:\n\n* Protects applications from development to production\n* Ensures compliance with security standards and regulations\n* Provides visibility into application security posture\n\n',
		related: []
	},
	{
		slug: 'pluggable-authentication-module',
		acronym: 'PAM',
		full_form: 'Pluggable Authentication Module',
		description:
			'PAM is a framework that provides a way to develop authentication-related programs in a modular fashion. It allows system administrators to choose how applications authenticate users without modifying the applications themselves.',
		markdown: '#todo',
		related: []
	},
	{
		slug: 'privileged-access-management',
		acronym: 'PAM',
		full_form: 'Privileged Access Management',
		description:
			'Privileged Access Management (PAM) refers to the processes and technologies used to control and monitor access to critical systems and sensitive information by privileged users. PAM solutions help organizations manage and secure privileged accounts, ensuring that only authorized users have access to sensitive resources.',
		markdown: '#todo',
		related: []
	},
	// security-information-and-event-management
	{
		slug: 'security-information-and-event-management',
		acronym: 'SIEM',
		full_form: 'Security Information and Event Management',
		description:
			'SIEM is a security management approach that combines security information management (SIM) and security event management (SEM) to provide real-time analysis of security alerts generated by applications and network hardware.',
		markdown: '#todo',
		related: []
	},
	// security-orchestration-automation-and-response
	{
		slug: 'security-orchestration-automation-and-response',
		acronym: 'SOAR',
		full_form: 'Security Orchestration, Automation, and Response',
		description:
			'SOAR refers to a set of tools and processes that enable organizations to collect security data and alerts from various sources, analyze them, and respond to incidents in an automated manner.',
		markdown: '#todo',
		related: []
	},
	// security-operations-center
	{
		slug: 'security-operations-center',
		acronym: 'SOC',
		full_form: 'Security Operations Center',
		description:
			'SOC is a centralized unit that deals with security issues on an organizational and technical level. It is responsible for monitoring, detecting, and responding to security incidents.',
		markdown: '#todo',
		related: []
	},
	// security-posture-management
	{
		slug: 'security-posture-management',
		acronym: 'SPM',
		full_form: 'Security Posture Management',
		description:
			"SPM refers to the processes and technologies used to assess and improve an organization's security posture. It involves continuous monitoring, assessment, and improvement of security controls and practices.",
		markdown: '#todo',
		related: []
	},
	// security-operations
	{
		slug: 'security-operations',
		acronym: 'SecOps',
		full_form: 'Security Operations',
		description:
			'SecOps refers to the integration of security practices into the operations of an organization. It aims to improve the security posture of an organization by ensuring that security is considered in all operational processes.',
		markdown: '#todo',
		related: []
	},
	// development-security-and-operations
	{
		slug: 'development-security-and-operations',
		acronym: 'DevSecOps',
		full_form: 'Development, Security, and Operations',
		description:
			'DevSecOps is a software development approach that integrates security practices into the DevOps process. It aims to ensure that security is considered at every stage of the software development lifecycle.',
		markdown: '#todo',
		related: []
	},
	// security-as-code
	{
		slug: 'security-as-code',
		acronym: 'SaC',
		full_form: 'Security as Code',
		description:
			'Security as Code refers to the practice of integrating security practices into the software development process. It aims to ensure that security is considered at every stage of the software development lifecycle.',
		markdown: '#todo',
		related: []
	},
	// application-layer-protocol-negotiation
	{
		slug: 'application-layer-protocol-negotiation',
		acronym: 'ALPN',
		full_form: 'Application Layer Protocol Negotiation',
		description:
			'ALPN is an extension to the Transport Layer Security (TLS) protocol that allows the application layer to negotiate which protocol to use over a secure connection. It is used in HTTP/2 and other protocols to improve performance and reduce latency.',
		markdown: '#todo',
		related: []
	},
	// application-programming-interface
	{
		slug: 'application-programming-interface',
		acronym: 'API',
		full_form: 'Application Programming Interface',
		description:
			'API is a set of rules and protocols for building and interacting with software applications. It defines the methods and data formats that applications can use to communicate with each other.',
		markdown: '#todo',
		related: []
	},
	// accessible-rich-internet-applications
	{
		slug: 'accessible-rich-internet-applications',
		acronym: 'ARIA',
		full_form: 'Accessible Rich Internet Applications',
		description:
			'ARIA is a set of attributes that can be added to HTML elements to improve accessibility for people with disabilities. It provides additional information about the roles, states, and properties of elements in web applications.',
		markdown: '#todo',
		related: []
	},
	// address-and-routing-parameter-area
	{
		slug: 'address-and-routing-parameter-area',
		acronym: 'ARPA',
		full_form: 'Address and Routing Parameter Area',
		description:
			'ARPA is a domain name used in the Domain Name System (DNS) to map IP addresses to hostnames. It is used for reverse DNS lookups, allowing users to find the hostname associated with an IP address.',
		markdown: '#todo',
		related: []
	},
	// advanced-research-projects-agency-network
	{
		slug: 'advanced-research-projects-agency-network',
		acronym: 'ARPANET',
		full_form: 'Advanced Research Projects Agency Network',
		description:
			'ARPANET was the first packet-switching network and the predecessor of the modern Internet. It was developed by the United States Department of Defense in the late 1960s to facilitate communication between research institutions.',
		markdown: '#todo',
		related: []
	},
	// american-standard-code-for-information-interchange
	{
		slug: 'american-standard-code-for-information-interchange',
		acronym: 'ASCII',
		full_form: 'American Standard Code for Information Interchange',
		description:
			'ASCII is a character encoding standard that uses numeric codes to represent characters. It is widely used in computers and communication equipment to represent text.',
		markdown: '#todo',
		related: []
	},
	// content-delivery-network
	{
		slug: 'content-delivery-network',
		acronym: 'CDN',
		full_form: 'Content Delivery Network',
		description:
			'A CDN is a network of servers distributed across multiple locations that work together to deliver content (such as web pages, images, and videos) to users based on their geographic location. CDNs improve the performance and reliability of content delivery by caching content closer to users.',
		markdown: '#todo',
		related: []
	},
	// confidentiality-integrity-availability
	{
		slug: 'confidentiality-integrity-availability',
		acronym: 'CIA',
		full_form: 'Confidentiality, Integrity, Availability',
		description:
			'CIA is a widely used model for information security that focuses on three core principles: confidentiality (ensuring that information is not disclosed to unauthorized individuals), integrity (ensuring that information is accurate and trustworthy), and availability (ensuring that information is accessible when needed).',
		markdown: '#todo',
		related: []
	},
	// cross-origin-resource-sharing
	{
		slug: 'cross-origin-resource-sharing',
		acronym: 'CORS',
		full_form: 'Cross-Origin Resource Sharing',
		description:
			'CORS is a security feature implemented in web browsers that allows or restricts web applications running at one origin to make requests to resources from a different origin. It is used to prevent cross-origin attacks and ensure secure communication between web applications.',
		markdown: '#todo',
		related: []
	},
	// carriage-return-line-feed
	{
		slug: 'carriage-return-line-feed',
		acronym: 'CRLF',
		full_form: 'Carriage Return Line Feed',
		description:
			'CRLF is a sequence of two control characters used to signify the end of a line in text files. It consists of a carriage return (CR) character followed by a line feed (LF) character.',
		markdown: '#todo',
		related: []
	},
	// create-read-update-delete
	{
		slug: 'create-read-update-delete',
		acronym: 'CRUD',
		full_form: 'Create, Read, Update, Delete',
		description:
			'CRUD is a set of four basic operations used in database management and web applications. It refers to the four fundamental functions of persistent storage.',
		markdown: '#todo',
		related: []
	},
	// content-security-policy
	{
		slug: 'content-security-policy',
		acronym: 'CSP',
		full_form: 'Content Security Policy',
		description:
			'CSP is a security feature that helps prevent various types of attacks, such as cross-site scripting (XSS) and data injection attacks. It allows web developers to specify which content sources are trusted and can be loaded by the browser.',
		markdown: '#todo',
		related: []
	},
	// cross-site-request-forgery
	{
		slug: 'cross-site-request-forgery',
		acronym: 'CSRF',
		full_form: 'Cross-Site Request Forgery',
		description:
			'CSRF is a type of attack that tricks the user into executing unwanted actions on a different website where they are authenticated. It exploits the trust that a site has in the user’s browser.',
		markdown: '#todo',
		related: []
	},
	// cross-site-scripting
	{
		slug: 'distributed-denial-of-service',
		acronym: 'DDoS',
		full_form: 'Distributed Denial of Service',
		description:
			'DDoS is a type of cyberattack in which multiple compromised systems are used to flood a target system with traffic, overwhelming it and causing it to become unavailable to legitimate users.',
		markdown: '#todo',
		related: []
	},
	// demilitarized-zone
	{
		slug: 'demilitarized-zone',
		acronym: 'DMZ',
		full_form: 'Demilitarized Zone',
		description:
			"A DMZ is a physical or logical subnetwork that contains and exposes an organization's external-facing services to an untrusted network, usually the Internet. It adds an additional layer of security to the local area network (LAN) by segregating it from the external network.",
		markdown: '#todo',
		related: []
	},
	// domain-name-system
	{
		slug: 'domain-name-system',
		acronym: 'DNS',
		full_form: 'Domain Name System',
		description:
			'DNS is a hierarchical and decentralized naming system used to translate human-readable domain names (like www.example.com) into IP addresses.',
		markdown: '#todo',
		related: []
	},
	// denial-of-service
	{
		slug: 'denial-of-service',
		acronym: 'DoS',
		full_form: 'Denial of Service',
		description:
			'DoS is a type of cyberattack that aims to make a machine or network resource unavailable to its intended users by overwhelming it with a flood of illegitimate requests.',
		markdown: '#todo',
		related: []
	},
	// digital-subscriber-line
	{
		slug: 'digital-subscriber-line',
		acronym: 'DSL',
		full_form: 'Digital Subscriber Line',
		description:
			'DSL is a family of technologies that provide digital data transmission over the wires of a local telephone network. It is commonly used for high-speed Internet access.',
		markdown: '#todo',
		related: []
	},
	// domain-specific-language
	{
		slug: 'domain-specific-language',
		acronym: 'DSL',
		full_form: 'Domain-Specific Language',
		description:
			'A DSL is a programming language or specification dedicated to a particular problem domain, a particular solution technique, or a particular language implementation technique.',
		markdown: '#todo',
		related: []
	},
	// data-loss-prevention
	{
		slug: 'data-loss-prevention',
		acronym: 'DLP',
		full_form: 'Data Loss Prevention',
		description:
			'DLP refers to a set of tools and processes used to ensure that sensitive data is not lost, misused, or accessed by unauthorized users. It helps organizations protect their data from breaches and leaks.',
		markdown: '#todo',
		related: []
	},
	// data-protection-officer
	{
		slug: 'data-protection-officer',
		acronym: 'DPO',
		full_form: 'Data Protection Officer',
		description:
			'A DPO is an individual responsible for overseeing data protection strategy and implementation to ensure compliance with data protection regulations.',
		markdown: '#todo',
		related: []
	},
	// datagram-transport-layer-security
	{
		slug: 'datagram-transport-layer-security',
		acronym: 'DTLS',
		full_form: 'Datagram Transport Layer Security',
		description:
			'DTLS is a communications protocol that provides privacy for datagram protocols. It is based on the Transport Layer Security (TLS) protocol and is used to secure communications over the Internet.',
		markdown: '#todo',
		related: []
	},
	// dual-tone-multi-frequency-signaling
	{
		slug: 'dual-tone-multi-frequency-signaling',
		acronym: 'DTMF',
		full_form: 'Dual Tone Multi Frequency Signaling',
		description:
			'DTMF is a signaling method used in telecommunication signaling over analog telephone lines in the voice-frequency band. It is used to dial telephone numbers and control automated systems.',
		markdown: '#todo',
		related: []
	},
	// extensible-markup-language
	{
		slug: 'european-computer-manufacturers-association',
		acronym: 'ECMA',
		full_form: 'European Computer Manufacturers Association',
		description:
			'ECMA is an industry association dedicated to the standardization of information and communication systems. It develops standards for programming languages, data interchange formats, and other technologies.',
		markdown: '#todo',
		related: []
	},
	// effective-top-level-domain
	{
		slug: 'effective-top-level-domain',
		acronym: 'eTLD',
		full_form: 'Effective Top-Level Domain',
		description:
			'eTLD is a domain name that represents the highest level of a domain name hierarchy. It is used to identify the type of organization or entity associated with the domain.',
		markdown: '#todo',
		related: []
	},
	// exchangeable-image-file-format
	{
		slug: 'exchangeable-image-file-format',
		acronym: 'EXIF',
		full_form: 'Exchangeable Image File Format',
		description:
			'EXIF is a standard for storing metadata in image files, particularly those taken with digital cameras. It includes information about the camera settings, date and time, and GPS location data.',
		markdown: '#todo',
		related: []
	},
	// file-transfer-protocol
	{
		slug: 'file-transfer-protocol',
		acronym: 'FTP',
		full_form: 'File Transfer Protocol',
		description:
			'FTP is a standard network protocol used to transfer files from one host to another over a TCP-based network. It is commonly used for uploading and downloading files to and from web servers.',
		markdown: '#todo',
		related: []
	},
	// first-time-use
	{
		slug: 'first-time-use',
		acronym: 'FTU',
		full_form: 'First Time Use',
		description:
			'FTU refers to the initial use of a product or service by a user. It is often used in the context of user experience design to ensure that the first interaction with a product is smooth and intuitive.',
		markdown: '#todo',
		related: []
	},
	// git-source-control-management
	{
		slug: 'git-source-control-management',
		acronym: 'GIT',
		full_form: 'Git Source Control Management',
		description:
			'Git is a distributed version control system used to track changes in source code during software development. It allows multiple developers to work on a project simultaneously and provides tools for collaboration and versioning.',
		markdown: '#todo',
		related: []
	},
	// general-public-license
	{
		slug: 'general-public-license',
		acronym: 'GPL',
		full_form: 'General Public License',
		description:
			'GPL is a widely used free software license that guarantees end users the freedom to run, study, share, and modify the software. It is designed to ensure that software remains free and open for all users.',
		markdown: '#todo',
		related: []
	},
	// graphics-processing-unit
	{
		slug: 'graphics-processing-unit',
		acronym: 'GPU',
		full_form: 'Graphics Processing Unit',
		description:
			'GPU is a specialized electronic circuit designed to accelerate the processing of images and videos. It is commonly used in gaming, video editing, and machine learning applications.',
		markdown: '#todo',
		related: []
	},
	// hash-based-message-authentication-code
	{
		slug: 'hash-based-message-authentication-code',
		acronym: 'HMAC',
		full_form: 'Hash-Based Message Authentication Code',
		description:
			'HMAC is a specific construction for creating a message authentication code (MAC) based on a cryptographic hash function. It is used to verify the integrity and authenticity of a message.',
		markdown: '#todo',
		related: []
	},
	// http-public-key-pinning
	{
		slug: 'http-public-key-pinning',
		acronym: 'HPKP',
		full_form: 'HTTP Public Key Pinning',
		description:
			'HPKP is a web security feature that allows HTTPS websites to resist impersonation by attackers using mis-issued or otherwise fraudulent certificates. It enables web servers to specify which public keys are valid for a given domain.',
		markdown: '#todo',
		related: []
	},
	// http-strict-transport-security
	{
		slug: 'http-strict-transport-security',
		acronym: 'HSTS',
		full_form: 'HTTP Strict Transport Security',
		description:
			"HSTS is a web security policy mechanism that helps protect websites' communications from downgrade attacks and cookie hijacking. It allows web servers to declare that web browsers should only interact with them using secure HTTPS connections.",
		markdown: '#todo',
		related: []
	},
	// hypertext-markup-language
	{
		slug: 'hypertext-markup-language',
		acronym: 'HTML',
		full_form: 'Hypertext Markup Language',
		description:
			'HTML is the standard markup language used to create web pages. It describes the structure of a web page using elements and tags.',
		markdown: '#todo',
		related: []
	},
	// hypertext-transfer-protocol
	{
		slug: 'hypertext-transfer-protocol',
		acronym: 'HTTP',
		full_form: 'Hypertext Transfer Protocol',
		description:
			'HTTP is an application protocol used for transmitting hypermedia documents, such as HTML, over the Internet. It is the foundation of data communication on the World Wide Web.',
		markdown: '#todo',
		related: []
	},
	// hypertext-transfer-protocol-secure
	{
		slug: 'hypertext-transfer-protocol-secure',
		acronym: 'HTTPS',
		full_form: 'Hypertext Transfer Protocol Secure',
		description:
			'HTTPS is an extension of HTTP that adds a layer of security on the data in transit. It uses Transport Layer Security (TLS) to encrypt the communication between the client and server.',
		markdown: '#todo',
		related: []
	},
	// https-resource-records
	{
		slug: 'https-resource-records',
		acronym: 'HTTPS RR',
		full_form: 'HTTPS Resource Records',
		description:
			'HTTPS RR is a type of DNS resource record that indicates the presence of an HTTPS service at a given domain name. It is used to improve the security and performance of HTTPS connections.',
		markdown: '#todo',
		related: []
	},
	// internationalization
	{
		slug: 'internationalization',
		acronym: 'i18n',
		full_form: 'Internationalization',
		description:
			'i18n is the process of designing a software application so that it can be adapted to various languages and regions without requiring engineering changes. It involves preparing the software for localization.',
		markdown: '#todo',
		related: []
	},
	// internet-assigned-numbers-authority
	{
		slug: 'internet-assigned-numbers-authority',
		acronym: 'IANA',
		full_form: 'Internet Assigned Numbers Authority',
		description:
			'IANA is a department of ICANN that oversees global IP address allocation, autonomous system number allocation, root zone management in the DNS, and other Internet protocol resources.',
		markdown: '#todo',
		related: []
	},
	// internet-corporation-for-assigned-names-and-numbers
	{
		slug: 'internet-corporation-for-assigned-names-and-numbers',
		acronym: 'ICANN',
		full_form: 'Internet Corporation for Assigned Names and Numbers',
		description:
			'ICANN is a nonprofit organization that coordinates the maintenance and procedures of several databases related to the namespaces and numerical spaces of the Internet.',
		markdown: '#todo',
		related: []
	},
	// interactive-connectivity-establishment
	{
		slug: 'interactive-connectivity-establishment',
		acronym: 'ICE',
		full_form: 'Interactive Connectivity Establishment',
		description:
			'ICE is a framework used to allow web browsers to connect with peers, such as other web browsers or servers, in a secure and efficient manner. It is commonly used in WebRTC applications.',
		markdown: '#todo',
		related: []
	},
	// integrated-development-environment
	{
		slug: 'integrated-development-environment',
		acronym: 'IDE',
		full_form: 'Integrated Development Environment',
		description:
			'IDE is a software application that provides comprehensive facilities to computer programmers for software development. It typically includes a code editor, debugger, and build automation tools.',
		markdown: '#todo',
		related: []
	},
	// interface-description-language
	{
		slug: 'interface-description-language',
		acronym: 'IDL',
		full_form: 'Interface Description Language',
		description:
			'IDL is a specification language used to describe software component interfaces. It allows different components to communicate with each other, regardless of the programming languages they are written in.',
		markdown: '#todo',
		related: []
	},
	// identity-provider
	{
		slug: 'identity-provider',
		acronym: 'IdP',
		full_form: 'Identity Provider',
		description:
			'An IdP is a system that creates, maintains, and manages identity information for principals while providing authentication services to applications within a federation or distributed network.',
		markdown: '#todo',
		related: []
	},
	// internet-engineering-task-force
	{
		slug: 'internet-engineering-task-force',
		acronym: 'IETF',
		full_form: 'Internet Engineering Task Force',
		description:
			'IETF is an open standards organization that develops and promotes voluntary Internet standards, particularly those related to the TCP/IP protocol suite.',
		markdown: '#todo',
		related: []
	},
	// immediately-invoked-function-expression
	{
		slug: 'immediately-invoked-function-expression',
		acronym: 'IIFE',
		full_form: 'Immediately Invoked Function Expression',
		description:
			'IIFE is a JavaScript function that runs as soon as it is defined. It is used to create a new scope and avoid polluting the global scope.',
		markdown: '#todo',
		related: []
	},
	// internet-message-access-protocol
	{
		slug: 'internet-message-access-protocol',
		acronym: 'IMAP',
		full_form: 'Internet Message Access Protocol',
		description:
			'IMAP is a protocol used by email clients to retrieve and manage email messages from a mail server. It allows users to access their email from multiple devices while keeping the messages stored on the server.',
		markdown: '#todo',
		related: []
	},
	// internet-protocol
	{
		slug: 'internet-protocol',
		acronym: 'IP',
		full_form: 'Internet Protocol',
		description:
			'IP is the principal communications protocol in the Internet protocol suite for relaying datagrams across network boundaries. It is responsible for addressing and routing packets of data.',
		markdown: '#todo',
		related: []
	},
	// internet-protocol-version-4
	{
		slug: 'internet-protocol-version-4',
		acronym: 'IPv4',
		full_form: 'Internet Protocol Version 4',
		description:
			'IPv4 is the fourth version of the Internet Protocol (IP) and is widely used to identify devices on a network through an addressing system. It uses a 32-bit address scheme allowing for over 4 billion unique addresses.',
		markdown: '#todo',
		related: []
	},
	// internet-protocol-version-6
	{
		slug: 'internet-protocol-version-6',
		acronym: 'IPv6',
		full_form: 'Internet Protocol Version 6',
		description:
			'IPv6 is the most recent version of the Internet Protocol (IP) designed to replace IPv4. It uses a 128-bit address scheme allowing for a vastly larger number of unique IP addresses.',
		markdown: '#todo',
		related: []
	},
	// internet-relay-chat
	{
		slug: 'internet-relay-chat',
		acronym: 'IRC',
		full_form: 'Internet Relay Chat',
		description:
			'IRC is a protocol for real-time Internet text messaging (chat) or synchronous conferencing. It allows users to communicate in channels or private messages.',
		markdown: '#todo',
		related: []
	},
	// international-organization-for-standardization
	{
		slug: 'international-organization-for-standardization',
		acronym: 'ISO',
		full_form: 'International Organization for Standardization',
		description:
			'ISO is an independent, non-governmental international organization that develops and publishes standards. It aims to ensure quality, safety, and efficiency across various industries.',
		markdown: '#todo',
		related: []
	},
	// internet-service-provider
	{
		slug: 'internet-service-provider',
		acronym: 'ISP',
		full_form: 'Internet Service Provider',
		description:
			'ISP is a company that provides individuals and organizations access to the Internet. ISPs may also provide additional services such as web hosting, email, and domain registration.',
		markdown: '#todo',
		related: []
	},
	// international-telecommunication-union
	{
		slug: 'international-telecommunication-union',
		acronym: 'ITU',
		full_form: 'International Telecommunication Union',
		description:
			'ITU is a specialized agency of the United Nations that is responsible for issues related to information and communication technologies. It coordinates the global use of the radio-frequency spectrum and satellite orbits.',
		markdown: '#todo',
		related: []
	},
	// just-in-time-compilation
	{
		slug: 'just-in-time-compilation',
		acronym: 'JIT',
		full_form: 'Just-In-Time Compilation',
		description:
			'JIT is a technique used in programming languages to improve the runtime performance of applications. It compiles code at runtime rather than before execution, allowing for optimizations based on the current execution context.',
		markdown: '#todo',
		related: []
	},
	// joint-photographic-experts-group
	{
		slug: 'joint-photographic-experts-group',
		acronym: 'JPEG',
		full_form: 'Joint Photographic Experts Group',
		description:
			'JPEG is a commonly used method of lossy compression for digital images, particularly for photographs. It is named after the committee that created the standard.',
		markdown: '#todo',
		related: []
	},
	// javascript-object-notation
	{
		slug: 'javascript-object-notation',
		acronym: 'JSON',
		full_form: 'JavaScript Object Notation',
		description:
			'JSON is an open standard format that uses human-readable text to transmit data objects consisting of attribute-value pairs. It is primarily used to transmit data between a server and web application as an alternative to XML.',
		markdown: '#todo',
		related: []
	},
	// gnu-lesser-general-public-license
	{
		slug: 'gnu-lesser-general-public-license',
		acronym: 'LGPL',
		full_form: 'GNU Lesser General Public License',
		description:
			'LGPL is a free software license published by the Free Software Foundation. It allows developers to use and integrate LGPL-licensed software into their own (even proprietary) software without being required to release the source code of their own software.',
		markdown: '#todo',
		related: []
	},
	// left-to-right
	{
		slug: 'left-to-right',
		acronym: 'LTR',
		full_form: 'Left to Right',
		description:
			'LTR refers to the direction in which text is read and written in languages such as English, French, and Spanish. It is the opposite of right-to-left (RTL) direction used in languages such as Arabic and Hebrew.',
		markdown: '#todo',
		related: []
	},
	// multipurpose-internet-mail-extensions
	{
		slug: 'multipurpose-internet-mail-extensions',
		acronym: 'MIME',
		full_form: 'Multipurpose Internet Mail Extensions',
		description:
			'MIME is an Internet standard that extends the format of email messages to support text in character sets other than ASCII, as well as attachments of audio, video, images, and application programs.',
		markdown: '#todo',
		related: []
	},
	// manipulator-in-the-middle-attack
	{
		slug: 'manipulator-in-the-middle-attack',
		acronym: 'MITM',
		full_form: 'Manipulator in the Middle Attack',
		description:
			'MITM is a type of cyberattack where the attacker secretly relays and possibly alters the communication between two parties who believe they are directly communicating with each other.',
		markdown: '#todo',
		related: []
	},
	// model-view-controller
	{
		slug: 'model-view-controller',
		acronym: 'MVC',
		full_form: 'Model View Controller',
		description:
			'MVC is a software architectural pattern for implementing user interfaces. It divides an application into three interconnected components: Model (data), View (UI), and Controller (business logic).',
		markdown: '#todo',
		related: []
	},
	// not-a-number
	{
		slug: 'not-a-number',
		acronym: 'NaN',
		full_form: 'Not a Number',
		description:
			'NaN is a numeric data type value representing an undefined or unrepresentable value, especially in floating-point calculations.',
		markdown: '#todo',
		related: []
	},
	// network-address-translation
	{
		slug: 'network-address-translation',
		acronym: 'NAT',
		full_form: 'Network Address Translation',
		description:
			'NAT is a method of remapping one IP address space into another by modifying network address information in the IP header of packets while they are in transit across a traffic routing device.',
		markdown: '#todo',
		related: []
	},
	// network-news-transfer-protocol
	{
		slug: 'network-news-transfer-protocol',
		acronym: 'NNTP',
		full_form: 'Network News Transfer Protocol',
		description:
			'NNTP is a protocol used for the distribution, inquiry, retrieval, and posting of Usenet articles using a reliable stream-based mechanism.',
		markdown: '#todo',
		related: []
	},
	// object-oriented-programming
	{
		slug: 'object-oriented-programming',
		acronym: 'OOP',
		full_form: 'Object-Oriented Programming',
		description:
			'OOP is a programming paradigm based on the concept of "objects", which can contain data and code: data in the form of fields (often known as attributes or properties), and code in the form of procedures (often known as methods).',
		markdown: '#todo',
		related: []
	},
	// over-the-air
	{
		slug: 'over-the-air',
		acronym: 'OTA',
		full_form: 'Over the Air',
		description:
			'OTA refers to the process of wirelessly delivering software updates, configuration settings, or other data to devices such as smartphones, tablets, and IoT devices.',
		markdown: '#todo',
		related: []
	},
	// open-web-application-security-project
	{
		slug: 'open-web-application-security-project',
		acronym: 'OWASP',
		full_form: 'Open Web Application Security Project',
		description:
			'OWASP is an open-source project that aims to improve the security of software. It provides unbiased, practical information about computer security and offers tools and resources for developers and organizations.',
		markdown: '#todo',
		related: []
	},
	// peer-to-peer
	{
		slug: 'peer-to-peer',
		acronym: 'P2P',
		full_form: 'Peer to Peer',
		description:
			'P2P is a decentralized communications model in which each party has the same capabilities and either party can initiate a communication session. It is commonly used in file sharing and distributed computing.',
		markdown: '#todo',
		related: []
	},
	// proxy-auto-configuration
	{
		slug: 'proxy-auto-configuration',
		acronym: 'PAC',
		full_form: 'Proxy Auto Configuration',
		description:
			'PAC is a file format used by web browsers to automatically select the appropriate proxy server for a given URL. It allows for dynamic configuration of proxy settings based on the URL being accessed.',
		markdown: '#todo',
		related: []
	},
	// portable-document-format
	{
		slug: 'portable-document-format',
		acronym: 'PDF',
		full_form: 'Portable Document Format',
		description:
			'PDF is a file format developed by Adobe that captures document text, fonts, graphics, and other information in a device-independent manner. It is widely used for sharing documents across different platforms.',
		markdown: '#todo',
		related: []
	},
	// hypertext-preprocessor
	{
		slug: 'hypertext-preprocessor',
		acronym: 'PHP',
		full_form: 'Hypertext Preprocessor',
		description:
			'PHP is a popular general-purpose scripting language that is especially suited to web development. It is fast, flexible, and pragmatic, and powers everything from your blog to the most popular websites in the world.',
		markdown: '#todo',
		related: []
	},
	// portable-network-graphics
	{
		slug: 'portable-network-graphics',
		acronym: 'PNG',
		full_form: 'Portable Network Graphics',
		description:
			'PNG is a raster graphics file format that supports lossless data compression. It is widely used for images on the web and supports transparency and a wide range of color depths.',
		markdown: '#todo',
		related: []
	},
	// post-office-protocol
	{
		slug: 'post-office-protocol',
		acronym: 'POP',
		full_form: 'Post Office Protocol',
		description:
			'POP is a protocol used by email clients to retrieve email from a mail server. It allows users to download their email messages to their local device for offline access.',
		markdown: '#todo',
		related: []
	},
	// post-office-protocol-version-3
	{
		slug: 'post-office-protocol-version-3',
		acronym: 'POP3',
		full_form: 'Post Office Protocol Version 3',
		description:
			'POP3 is the third version of the Post Office Protocol and is used by email clients to retrieve email from a mail server. It allows users to download their email messages to their local device for offline access.',
		markdown: '#todo',
		related: []
	},
	// quick-udp-internet-connections
	{
		slug: 'quick-udp-internet-connections',
		acronym: 'QUIC',
		full_form: 'Quick UDP Internet Connections',
		description:
			'QUIC is a transport layer network protocol designed by Google to provide secure and low-latency connections. It is used in web applications to improve performance and security.',
		markdown: '#todo',
		related: []
	},
	// resource-description-framework
	{
		slug: 'resource-description-framework',
		acronym: 'RDF',
		full_form: 'Resource Description Framework',
		description:
			'RDF is a standard model for data interchange on the web. It provides a framework for representing information about resources in a graph form, allowing for easy sharing and reuse of data across different applications.',
		markdown: '#todo',
		related: []
	},
	// representational-state-transfer
	{
		slug: 'representational-state-transfer',
		acronym: 'REST',
		full_form: 'Representational State Transfer',
		description:
			'REST is an architectural style for designing networked applications. It relies on a stateless, client-server communication model and uses standard HTTP methods for interaction.',
		markdown: '#todo',
		related: []
	},
	// radio-interface-layer
	{
		slug: 'radio-interface-layer',
		acronym: 'RIL',
		full_form: 'Radio Interface Layer',
		description:
			'RIL is a software layer that provides an interface between the radio hardware and the operating system in mobile devices. It is responsible for managing radio resources and communication with the network.',
		markdown: '#todo',
		related: []
	},
	// really-simple-syndication
	{
		slug: 'really-simple-syndication',
		acronym: 'RSS',
		full_form: 'Really Simple Syndication',
		description:
			'RSS is a web feed format used to publish frequently updated content, such as blog posts, news articles, and podcasts. It allows users to subscribe to content and receive updates automatically.',
		markdown: '#todo',
		related: []
	},
	// rtp-control-protocol
	{
		slug: 'rtp-control-protocol',
		acronym: 'RTCP',
		full_form: 'RTP Control Protocol',
		description:
			'RTCP is a network control protocol for RTP that provides out-of-band statistics and control information for an RTP flow. It is used to monitor the quality of service and convey information about the participants in an RTP session.',
		markdown: '#todo',
		related: []
	},
	// rich-text-format
	{
		slug: 'rich-text-format',
		acronym: 'RTF',
		full_form: 'Rich Text Format',
		description:
			'RTF is a file format used for text documents that supports text formatting, such as bold, italics, and different fonts. It is widely used for document exchange between different word processors.',
		markdown: '#todo',
		related: []
	},
	// right-to-left
	{
		slug: 'right-to-left',
		acronym: 'RTL',
		full_form: 'Right to Left',
		description:
			'RTL refers to the direction in which text is read and written in languages such as Arabic and Hebrew. It is the opposite of left-to-right (LTR) direction used in languages such as English, French, and Spanish.',
		markdown: '#todo',
		related: []
	},
	// real-time-transport-protocol
	{
		slug: 'real-time-transport-protocol',
		acronym: 'RTP',
		full_form: 'Real-Time Transport Protocol',
		description:
			'RTP is a network protocol for delivering audio and video over IP networks. It is used in applications that require real-time transmission, such as video conferencing and streaming media.',
		markdown: '#todo',
		related: []
	},
	// real-time-streaming-protocol
	{
		slug: 'real-time-streaming-protocol',
		acronym: 'RTSP',
		full_form: 'Real-Time Streaming Protocol',
		description:
			'RTSP is a network control protocol designed for use in entertainment and communications systems to control streaming media servers. It allows clients to remotely control media streams.',
		markdown: '#todo',
		related: []
	},
	// round-trip-time
	{
		slug: 'round-trip-time',
		acronym: 'RTT',
		full_form: 'Round Trip Time',
		description:
			'RTT is the time it takes for a signal to travel from the sender to the receiver and back again. It is commonly used as a measure of latency in network communications.',
		markdown: '#todo',
		related: []
	},
	// real-user-monitoring
	{
		slug: 'real-user-monitoring',
		acronym: 'RUM',
		full_form: 'Real User Monitoring',
		description:
			'RUM is a performance measurement technique that captures and analyzes the behavior of real users as they interact with a website or application. It provides insights into user experience and performance metrics.',
		markdown: '#todo',
		related: []
	},
	// source-control-management
	{
		slug: 'source-control-management',
		acronym: 'SCM',
		full_form: 'Source Control Management',
		description:
			'SCM is the management of changes to documents, computer programs, and other collections of information. It is used to track revisions and control changes to source code in software development.',
		markdown: '#todo',
		related: []
	},
	// stream-control-transmission-protocol
	{
		slug: 'stream-control-transmission-protocol',
		acronym: 'SCTP',
		full_form: 'Stream Control Transmission Protocol',
		description:
			'SCTP is a transport layer protocol used to transmit multiple streams of data between two endpoints. It is designed to provide reliable, message-oriented communication and is used in applications such as telephony and video conferencing.',
		markdown: '#todo',
		related: []
	},
	// software-development-kit
	{
		slug: 'software-development-kit',
		acronym: 'SDK',
		full_form: 'Software Development Kit',
		description:
			'An SDK is a collection of software development tools that allows developers to create applications for specific platforms or frameworks. It typically includes libraries, documentation, and sample code.',
		markdown: '#todo',
		related: []
	},
	// session-description-protocol
	{
		slug: 'session-description-protocol',
		acronym: 'SDP',
		full_form: 'Session Description Protocol',
		description:
			'SDP is a format for describing multimedia communication sessions for the purposes of session announcement, session invitation, and other forms of multimedia session initiation. It is used in protocols such as SIP and RTP.',
		markdown: '#todo',
		related: []
	},
	// standard-generalized-markup-language
	{
		slug: 'standard-generalized-markup-language',
		acronym: 'SGML',
		full_form: 'Standard Generalized Markup Language',
		description:
			'SGML is a standard for defining generalized markup languages for documents. It is the basis for HTML and XML and provides a framework for defining the structure and content of documents.',
		markdown: '#todo',
		related: []
	},
	// single-instruction-multiple-data
	{
		slug: 'single-instruction-multiple-data',
		acronym: 'SIMD',
		full_form: 'Single Instruction Multiple Data',
		description:
			'SIMD is a parallel computing architecture that allows a single instruction to be executed on multiple data points simultaneously. It is commonly used in vector processors and graphics processing units (GPUs).',
		markdown: '#todo',
		related: []
	},
	// single-instruction-single-data
	{
		slug: 'single-instruction-single-data',
		acronym: 'SISD',
		full_form: 'Single Instruction Single Data',
		description:
			'SISD is a computer architecture where a single instruction operates on a single data point at a time. It is the simplest form of computer architecture and is used in traditional von Neumann architectures.',
		markdown: '#todo',
		related: []
	},
	// second-level-domain
	{
		slug: 'second-level-domain',
		acronym: 'SLD',
		full_form: 'Second Level Domain',
		description:
			'SLD is the part of a domain name that is to the left of the top-level domain (TLD). It is used to identify a specific organization or entity within a domain.',
		markdown: '#todo',
		related: []
	},
	// society-of-motion-picture-and-television-engineers
	{
		slug: 'society-of-motion-picture-and-television-engineers',
		acronym: 'SMPTE',
		full_form: 'Society of Motion Picture and Television Engineers',
		description:
			'SMPTE is a professional association that develops standards for the motion picture and television industries. It is known for its work in developing standards for video and audio formats.',
		markdown: '#todo',
		related: []
	},
	// simple-mail-transfer-protocol
	{
		slug: 'simple-mail-transfer-protocol',
		acronym: 'SMTP',
		full_form: 'Simple Mail Transfer Protocol',
		description:
			'SMTP is a protocol used for sending email messages between servers. It is a text-based protocol that allows for the transfer of email messages over the Internet.',
		markdown: '#todo',
		related: []
	},
	// simple-object-access-protocol
	{
		slug: 'simple-object-access-protocol',
		acronym: 'SOAP',
		full_form: 'Simple Object Access Protocol',
		description:
			'SOAP is a protocol for exchanging structured information in the implementation of web services. It relies on XML-based messaging and is used to communicate between applications over the Internet.',
		markdown: '#todo',
		related: []
	},
	// same-origin-policy
	{
		slug: 'same-origin-policy',
		acronym: 'SOP',
		full_form: 'Same Origin Policy',
		description:
			'SOP is a security measure implemented in web browsers that restricts how documents or scripts loaded from one origin can interact with resources from another origin. It is designed to prevent cross-site scripting attacks.',
		markdown: '#todo',
		related: []
	},
	// single-page-application
	{
		slug: 'single-page-application',
		acronym: 'SPA',
		full_form: 'Single Page Application',
		description:
			'SPA is a web application that interacts with the user by dynamically rewriting the current page, rather than loading entire new pages from the server. This approach allows for a more fluid user experience.',
		markdown: '#todo',
		related: []
	},
	// structured-query-language
	{
		slug: 'structured-query-language',
		acronym: 'SQL',
		full_form: 'Structured Query Language',
		description:
			'SQL is a standardized programming language used for managing and manipulating relational databases. It is used to perform tasks such as querying, updating, and deleting data.',
		markdown: '#todo',
		related: []
	},
	// subresource-integrity
	{
		slug: 'subresource-integrity',
		acronym: 'SRI',
		full_form: 'Subresource Integrity',
		description:
			'SRI is a security feature that enables browsers to verify that fetched resources are delivered without unexpected manipulation. It allows for the use of a cryptographic hash to ensure the integrity of the resource.',
		markdown: '#todo',
		related: []
	},
	// secure-rtp
	{
		slug: 'secure-rtp',
		acronym: 'SRTP',
		full_form: 'Secure Real-Time Transport Protocol',
		description:
			'SRTP is a profile of RTP that provides encryption, message authentication, and integrity, and replay protection to the RTP data in real-time applications such as voice and video conferencing.',
		markdown: '#todo',
		related: []
	},
	// static-site-generator
	{
		slug: 'static-site-generator',
		acronym: 'SSG',
		full_form: 'Static Site Generator',
		description:
			'SSG is a tool that generates static HTML pages from source files. It is commonly used to create fast and secure websites that do not require a database or server-side processing.',
		markdown: '#todo',
		related: []
	},
	// secure-sockets-layer
	{
		slug: 'secure-sockets-layer',
		acronym: 'SSL',
		full_form: 'Secure Sockets Layer',
		description:
			'SSL is a standard security technology for establishing an encrypted link between a server and a client. It is used to secure data transmitted over the Internet and is the predecessor to TLS.',
		markdown: '#todo',
		related: []
	},
	// server-side-rendering
	{
		slug: 'server-side-rendering',
		acronym: 'SSR',
		full_form: 'Server Side Rendering',
		description:
			'SSR is a technique used in web development where the server generates the HTML for a web page and sends it to the client. This approach can improve performance and SEO compared to client-side rendering.',
		markdown: '#todo',
		related: []
	},
	// session-traversal-utilities-for-nat
	{
		slug: 'session-traversal-utilities-for-nat',
		acronym: 'STUN',
		full_form: 'Session Traversal Utilities for NAT',
		description:
			'STUN is a protocol used to allow applications to discover the presence and types of NATs and firewalls between them and the public Internet. It is commonly used in VoIP and WebRTC applications.',
		markdown: '#todo',
		related: []
	},
	// scalable-vector-graphics
	{
		slug: 'scalable-vector-graphics',
		acronym: 'SVG',
		full_form: 'Scalable Vector Graphics',
		description:
			'SVG is an XML-based vector image format for two-dimensional graphics with support for interactivity and animation. It is widely used for web graphics and can be styled with CSS.',
		markdown: '#todo',
		related: []
	},
	// apache-subversion
	{
		slug: 'apache-subversion',
		acronym: 'SVN',
		full_form: 'Apache Subversion',
		description:
			'SVN is a version control system that is used to manage changes to files and directories over time. It allows multiple users to collaborate on projects and track changes to the source code.',
		markdown: '#todo',
		related: []
	},
	// transmission-control-protocol
	{
		slug: 'transmission-control-protocol',
		acronym: 'TCP',
		full_form: 'Transmission Control Protocol',
		description:
			'TCP is a core protocol of the Internet Protocol Suite that enables reliable, ordered, and error-checked delivery of data between applications running on hosts communicating over an IP network.',
		markdown: '#todo',
		related: []
	},
	// top-level-domain
	{
		slug: 'top-level-domain',
		acronym: 'TLD',
		full_form: 'Top Level Domain',
		description:
			'TLD is the last segment of a domain name, following the final dot. It is used to identify the type or category of a domain, such as .com, .org, or .net.',
		markdown: '#todo',
		related: []
	},
	// transport-layer-security
	{
		slug: 'transport-layer-security',
		acronym: 'TLS',
		full_form: 'Transport Layer Security',
		description:
			'TLS is a cryptographic protocol designed to provide secure communication over a computer network. It is widely used to secure web traffic and is the successor to SSL.',
		markdown: '#todo',
		related: []
	},
	// tunneled-transport-layer-security
	{
		slug: 'tunneled-transport-layer-security',
		acronym: 'TTLS',
		full_form: 'Tunneled Transport Layer Security',
		description:
			'TTLS is an extension of the TLS protocol that allows for secure communication over a network. It is commonly used in wireless networks to provide secure authentication and encryption.',
		markdown: '#todo',
		related: []
	},
	// trust-on-first-use
	{
		slug: 'trust-on-first-use',
		acronym: 'TOFU',
		full_form: 'Trust On First Use',
		description:
			'TOFU is a security model where the first time a user connects to a service, they trust the service without verifying its identity. This model is commonly used in SSH and other secure communications.',
		markdown: '#todo',
		related: []
	},
	// time-to-live
	{
		slug: 'time-to-live',
		acronym: 'TTL',
		full_form: 'Time To Live',
		description:
			'TTL is a field in the header of an IP packet that specifies the maximum time the packet is allowed to remain in the network before being discarded. It is used to prevent packets from circulating indefinitely.',
		markdown: '#todo',
		related: []
	},
	// traversal-using-relays-around-nat
	{
		slug: 'traversal-using-relays-around-nat',
		acronym: 'TURN',
		full_form: 'Traversal Using Relays around NAT',
		description:
			'TURN is a protocol that allows clients behind NATs to communicate with each other by relaying their media streams through a TURN server. It is commonly used in VoIP and WebRTC applications.',
		markdown: '#todo',
		related: []
	},
	// universal-coded-character-set-unicode
	{
		slug: 'universal-coded-character-set-unicode',
		acronym: 'UCS',
		full_form: 'Universal Coded Character Set - Unicode',
		description:
			'UCS is a character encoding standard that defines a comprehensive set of characters and symbols used in writing systems around the world. It is the basis for Unicode, which is widely used in modern computing.',
		markdown: '#todo',
		related: []
	},
	// user-datagram-protocol
	{
		slug: 'user-datagram-protocol',
		acronym: 'UDP',
		full_form: 'User Datagram Protocol',
		description:
			'UDP is a communication protocol used across the Internet for especially time-sensitive transmissions such as video playback or gaming. It is a connectionless protocol that does not guarantee delivery or order of packets.',
		markdown: '#todo',
		related: []
	},
	// user-interface
	{
		slug: 'user-interface',
		acronym: 'UI',
		full_form: 'User Interface',
		description:
			'UI refers to the means by which a user interacts with a computer, software application, or hardware device. It includes elements such as buttons, menus, and icons that allow users to navigate and control the system.',
		markdown: '#todo',
		related: []
	},
	// uniform-resource-identifier
	{
		slug: 'uniform-resource-identifier',
		acronym: 'URI',
		full_form: 'Uniform Resource Identifier',
		description:
			'URI is a string of characters that uniquely identifies a particular resource. It can be used to identify resources on the Internet, such as web pages, images, and files.',
		markdown: '#todo',
		related: []
	},
	// uniform-resource-locator
	{
		slug: 'uniform-resource-locator',
		acronym: 'URL',
		full_form: 'Uniform Resource Locator',
		description:
			'URL is a specific type of URI that provides the means to access a resource on the Internet. It typically includes the protocol (such as HTTP or HTTPS), domain name, and path to the resource.',
		markdown: '#todo',
		related: []
	},
	// uniform-resource-name
	{
		slug: 'uniform-resource-name',
		acronym: 'URN',
		full_form: 'Uniform Resource Name',
		description:
			'URN is a type of URI that uses a specific syntax to identify a resource by name in a particular namespace. It is intended to serve as a persistent, location-independent resource identifier.',
		markdown: '#todo',
		related: []
	},
	// ucs-transformation-format-8
	{
		slug: 'ucs-transformation-format-8',
		acronym: 'UTF-8',
		full_form: 'UCS Transformation Format 8',
		description:
			'UTF-8 is a variable-width character encoding used for electronic communication. It can represent every character in the Unicode character set and is backward compatible with ASCII.',
		markdown: '#todo',
		related: []
	},
	// universally-unique-identifier
	{
		slug: 'universally-unique-identifier',
		acronym: 'UUID',
		full_form: 'Universally Unique Identifier',
		description:
			'UUID is a 128-bit number used to uniquely identify information in computer systems. It is commonly used in software development to ensure that identifiers are unique across different systems and applications.',
		markdown: '#todo',
		related: []
	},
	// voice-over-internet-protocol
	{
		slug: 'voice-over-internet-protocol',
		acronym: 'VoIP',
		full_form: 'Voice Over Internet Protocol',
		description:
			'VoIP is a technology that allows for the delivery of voice communications and multimedia sessions over Internet Protocol (IP) networks. It enables users to make voice calls using the Internet instead of traditional telephone lines.',
		markdown: '#todo',
		related: []
	},
	// world-wide-web-consortium
	{
		slug: 'world-wide-web-consortium',
		acronym: 'W3C',
		full_form: 'World Wide Web Consortium',
		description:
			'W3C is an international community that develops open standards to ensure the long-term growth of the Web. It is responsible for creating and maintaining web standards such as HTML, CSS, and XML.',
		markdown: '#todo',
		related: []
	},
	// web-accessibility-initiative
	{
		slug: 'web-accessibility-initiative',
		acronym: 'WAI',
		full_form: 'Web Accessibility Initiative',
		description:
			'WAI is an initiative of the W3C that develops strategies, guidelines, and resources to help make the Web accessible to people with disabilities. It aims to ensure that all users can access and use web content.',
		markdown: '#todo',
		related: []
	},
	// web-hypertext-application-technology-working-group
	{
		slug: 'web-hypertext-application-technology-working-group',
		acronym: 'WHATWG',
		full_form: 'Web Hypertext Application Technology Working Group',
		description:
			'WHATWG is a community of people interested in evolving the web through standards and specifications. It focuses on the development of HTML and DOM standards.',
		markdown: '#todo',
		related: []
	},
	// xml-http-request
	{
		slug: 'xml-http-request',
		acronym: 'XHR',
		full_form: 'XML Http Request',
		description:
			'XHR is an API in web browsers that allows for the transfer of data between a web client and a server. It is commonly used to request and send data asynchronously without refreshing the page.',
		markdown: '#todo',
		related: []
	},
	// extensible-markup-language
	{
		slug: 'extensible-markup-language',
		acronym: 'XML',
		full_form: 'Extensible Markup Language',
		description:
			'XML is a markup language that defines a set of rules for encoding documents in a format that is both human-readable and machine-readable. It is widely used for data interchange on the web.',
		markdown: '#todo',
		related: []
	},
	// extensible-stylesheet-language-transformations
	{
		slug: 'extensible-stylesheet-language-transformations',
		acronym: 'XSLT',
		full_form: 'Extensible Stylesheet Language Transformations',
		description:
			'XSLT is a language for transforming XML documents into other formats, such as HTML or plain text. It is part of the XSL family of languages and is used to apply stylesheets to XML documents.',
		markdown: '#todo',
		related: []
	},
	// cross-site-scripting
	{
		slug: 'cross-site-scripting',
		acronym: 'XSS',
		full_form: 'Cross-Site Scripting',
		description:
			'XSS is a security vulnerability that allows attackers to inject malicious scripts into web pages viewed by other users. It can be used to steal information, hijack user sessions, and perform other malicious actions.',
		markdown: '#todo',
		related: []
	},
	// extensible-application-markup-language
	{
		slug: 'extensible-application-markup-language',
		acronym: 'XAML',
		full_form: 'Extensible Application Markup Language',
		description:
			'XAML is a declarative XML-based language used to define user interfaces in Windows applications. It is commonly used in technologies such as WPF (Windows Presentation Foundation) and UWP (Universal Windows Platform).',
		markdown: '#todo',
		related: []
	},
	// intrusion-detection-system
	{
		slug: 'intrusion-detection-system',
		acronym: 'IDS',
		full_form: 'Intrusion Detection System',
		description:
			'IDS is a device or software application that monitors a network or system for malicious activity or policy violations. It can detect and respond to potential threats in real-time.',
		markdown: '#todo',
		related: []
	},
	// intrusion-prevention-system
	{
		slug: 'intrusion-prevention-system',
		acronym: 'IPS',
		full_form: 'Intrusion Prevention System',
		description:
			'IPS is a network security technology that monitors network traffic for malicious activity and can take action to prevent it. It is often used in conjunction with firewalls and intrusion detection systems.',
		markdown: '#todo',
		related: []
	},
	// intrusion-detection-and-prevention-system
	{
		slug: 'intrusion-detection-and-prevention-system',
		acronym: 'IDPS',
		full_form: 'Intrusion Detection and Prevention System',
		description:
			'IDPS is a combination of intrusion detection and prevention systems that work together to monitor network traffic for malicious activity and take action to prevent it. It provides a comprehensive security solution for networks.',
		markdown: '#todo',
		related: []
	},
	// internet-of-things
	{
		slug: 'internet-of-things',
		acronym: 'IoT',
		full_form: 'Internet of Things',
		description:
			'IoT refers to the interconnection of everyday objects and devices to the Internet, allowing them to send and receive data. It enables smart devices to communicate and interact with each other and with users.',
		markdown: '#todo',
		related: []
	},
	// remote-authentication-dial-in-user-service
	{
		slug: 'remote-authentication-dial-in-user-service',
		acronym: 'RADIUS',
		full_form: 'Remote Authentication Dial In User Service',
		description:
			'RADIUS is a networking protocol that provides centralized Authentication, Authorization, and Accounting (AAA) management for users who connect and use a network service.',
		markdown: '#todo',
		related: []
	},
	// virtual-local-area-network
	{
		slug: 'virtual-local-area-network',
		acronym: 'VLAN',
		full_form: 'Virtual Local Area Network',
		description:
			'VLAN is a logical grouping of devices on a local area network (LAN) that allows for segmentation and isolation of network traffic. It improves network performance and security by separating different types of traffic.',
		markdown: '#todo',
		related: []
	},
	// virtual-private-network
	{
		slug: 'virtual-private-network',
		acronym: 'VPN',
		full_form: 'Virtual Private Network',
		description:
			'VPN is a technology that creates a secure and encrypted connection over a less secure network, such as the Internet. It allows users to send and receive data as if their devices were directly connected to a private network.',
		markdown: '#todo',
		related: []
	},
	// network-access-control
	{
		slug: 'network-access-control',
		acronym: 'NAC',
		full_form: 'Network Access Control',
		description:
			'NAC is a security solution that enforces policies on devices attempting to access a network. It ensures that only authorized and compliant devices can connect to the network, enhancing security and reducing risks.',
		markdown: '#todo',
		related: []
	},
	// simple-network-management-protocol
	{
		slug: 'simple-network-management-protocol',
		acronym: 'SNMP',
		full_form: 'Simple Network Management Protocol',
		description:
			'SNMP is a standard protocol used for managing devices on IP networks. It allows network administrators to monitor and control network devices, such as routers and switches, and gather performance data.',
		markdown: '#todo',
		related: []
	},
	// identity-access-management
	{
		slug: 'identity-access-management',
		acronym: 'IAM',
		full_form: 'Identity Access Management',
		description:
			'IAM is a framework of policies and technologies that ensures the right individuals have the appropriate access to technology resources. It includes user identity management, authentication, and authorization.',
		markdown: '#todo',
		related: []
	},
	// multi-factor-authentication
	{
		slug: 'multi-factor-authentication',
		acronym: 'MFA',
		full_form: 'Multi-Factor Authentication',
		description:
			'MFA is a security mechanism that requires users to provide two or more verification factors to gain access to a resource, such as an application or online account. It enhances security by adding additional layers of authentication.',
		markdown: '#todo',
		related: []
	},
	// third-party-risk-management
	{
		slug: 'third-party-risk-management',
		acronym: 'TPRM',
		full_form: 'Third Party Risk Management',
		description:
			'TPRM is the process of identifying, assessing, and managing risks associated with third-party vendors and service providers. It helps organizations mitigate potential risks that could arise from their relationships with external parties.',
		markdown: '#todo',
		related: []
	},
	// chief-information-security-officer
	{
		slug: 'chief-information-security-officer',
		acronym: 'CISO',
		full_form: 'Chief Information Security Officer',
		description:
			"CISO is a senior executive responsible for an organization's information and data security. They oversee the development and implementation of security policies, procedures, and strategies to protect the organization's assets.",
		markdown: '#todo',
		related: []
	},
	// chief-technology-officer
	{
		slug: 'chief-technology-officer',
		acronym: 'CTO',
		full_form: 'Chief Technology Officer',
		description:
			'CTO is a senior executive responsible for the technological direction of an organization. They oversee the development and implementation of technology strategies, ensuring that technology aligns with business goals.',
		markdown: '#todo',
		related: []
	},
	// chief-security-officer
	{
		slug: 'chief-security-officer',
		acronym: 'CSO',
		full_form: 'Chief Security Officer',
		description:
			"CSO is a senior executive responsible for the security of an organization's physical and digital assets. They oversee security policies, procedures, and strategies to protect the organization from threats.",
		markdown: '#todo',
		related: []
	},
	// supplier-information-security-requirements
	{
		slug: 'supplier-information-security-requirements',
		acronym: 'SISR',
		full_form: 'Supplier Information Security Requirements',
		description:
			'SISR refers to the security requirements that organizations impose on their suppliers to ensure the protection of sensitive information and data. It helps organizations manage third-party risks and maintain security standards.',
		markdown: '#todo',
		related: []
	},
	// continuous-cyber-risk-management
	{
		slug: 'continuous-cyber-risk-management',
		acronym: 'CCRM',
		full_form: 'Continuous Cyber Risk Management',
		description:
			'CCRM is an ongoing process of identifying, assessing, and mitigating cyber risks to an organization. It involves continuous monitoring and evaluation of security measures to adapt to evolving threats.',
		markdown: '#todo',
		related: []
	},
	// endpoint-detection-and-response
	{
		slug: 'endpoint-detection-and-response',
		acronym: 'EDR',
		full_form: 'Endpoint Detection and Response',
		description:
			'EDR is a security solution that monitors and responds to threats on endpoints, such as computers and mobile devices. It provides real-time visibility and analysis of endpoint activity to detect and respond to security incidents.',
		markdown: '#todo',
		related: []
	},
	// extended-detection-and-response
	{
		slug: 'extended-detection-and-response',
		acronym: 'XDR',
		full_form: 'Extended Detection and Response',
		description:
			"XDR is a security solution that integrates multiple security products into a unified platform for threat detection and response. It provides a holistic view of security events across an organization's environment.",
		markdown: '#todo',
		related: []
	},
	// managed-detection-and-response
	{
		slug: 'managed-detection-and-response',
		acronym: 'MDR',
		full_form: 'Managed Detection and Response',
		description:
			'MDR is a security service that provides organizations with threat detection and response capabilities. It combines advanced technology with human expertise to monitor, detect, and respond to security incidents.',
		markdown: '#todo',
		related: []
	},
	// automatic-certificate-management-environment
	{
		slug: 'automatic-certificate-management-environment',
		acronym: 'ACME',
		full_form: 'Automatic Certificate Management Environment',
		description:
			'ACME is a protocol used to automate the process of managing SSL/TLS certificates. It allows web servers to automatically obtain and renew certificates from a certificate authority, simplifying the management of secure connections.',
		markdown: '#todo',
		related: []
	},
	// certificate-authority
	{
		slug: 'certificate-authority',
		acronym: 'CA',
		full_form: 'Certificate Authority',
		description:
			'CA is an entity that issues digital certificates to verify the identity of individuals, organizations, or devices. It plays a crucial role in establishing trust in online communications and transactions.',
		markdown: '#todo',
		related: []
	},
	// certificate-signing-request
	{
		slug: 'certificate-signing-request',
		acronym: 'CSR',
		full_form: 'Certificate Signing Request',
		description:
			'CSR is a message sent from an applicant to a certificate authority to apply for a digital certificate. It contains information about the applicant and the public key that will be included in the certificate.',
		markdown: '#todo',
		related: []
	},
	// certificate-transparency
	{
		slug: 'certificate-transparency',
		acronym: 'CT',
		full_form: 'Certificate Transparency',
		description:
			'CT is a framework for monitoring and auditing digital certificates to prevent the issuance of fraudulent certificates. It provides a public log of all issued certificates, enhancing security and trust in the certificate ecosystem.',
		markdown: '#todo',
		related: []
	},
	// computer-generated-imagery
	{
		slug: 'computer-generated-imagery',
		acronym: 'CGI',
		full_form: 'Computer Generated Imagery',
		description:
			'CGI refers to the creation of still or animated visual content with computer software. It is widely used in movies, video games, and virtual reality applications to create realistic images and animations.',
		markdown: '#todo',
		related: []
	},
	// personally-identifiable-information
	{
		slug: 'personally-identifiable-information',
		acronym: 'PII',
		full_form: 'Personally Identifiable Information',
		description:
			'PII is any information that can be used to identify an individual, such as name, address, phone number, and social security number. It is subject to privacy regulations and must be protected to prevent identity theft and data breaches.',
		markdown: '#todo',
		related: []
	},
	// network-access-control
	{
		slug: 'network-access-control',
		acronym: 'NAC',
		full_form: 'Network Access Control',
		description:
			'NAC is a security solution that enforces policies on devices attempting to access a network. It ensures that only authorized and compliant devices can connect to the network, helping to protect against unauthorized access and threats.',
		markdown: '#todo',
		related: []
	},
	// zero-trust-network-access
	{
		slug: 'zero-trust-network-access',
		acronym: 'ZTNA',
		full_form: 'Zero Trust Network Access',
		description:
			'ZTNA is a security model that requires strict identity verification for every person and device trying to access resources on a private network, regardless of whether they are inside or outside the network perimeter.',
		markdown: '#todo',
		related: []
	},
	// cloud-access-security-broker
	{
		slug: 'cloud-access-security-broker',
		acronym: 'CASB',
		full_form: 'Cloud Access Security Broker',
		description:
			'CASB is a security policy enforcement point placed between cloud service consumers and providers to enforce security policies as cloud-based resources are accessed. It provides visibility and control over data in the cloud.',
		markdown: '#todo',
		related: []
	},
	// security-service-edge
	{
		slug: 'security-service-edge',
		acronym: 'SSE',
		full_form: 'Security Service Edge',
		description:
			'SSE is a cloud-based security model that provides security services such as secure web gateway, CASB, and zero trust network access. It is designed to protect users and data in a cloud-first environment.',
		markdown: '#todo',
		related: []
	},
	// secure-access-service-edge
	{
		slug: 'secure-access-service-edge',
		acronym: 'SASE',
		full_form: 'Secure Access Service Edge',
		description:
			'SASE is a cloud-based security architecture that combines network security functions with wide area networking (WAN) capabilities. It provides secure access to applications and data regardless of location.',
		markdown: '#todo',
		related: []
	},
	// remote-browser-isolation
	{
		slug: 'remote-browser-isolation',
		acronym: 'RBI',
		full_form: 'Remote Browser Isolation',
		description:
			'RBI is a security technology that isolates web browsing activity from the endpoint device. It prevents malware and other threats from reaching the device by executing web content in a remote environment.',
		markdown: '#todo',
		related: []
	},
	// secure-web-gateway
	{
		slug: 'secure-web-gateway',
		acronym: 'SWG',
		full_form: 'Secure Web Gateway',
		description:
			'SWG is a security solution that protects users from web-based threats by filtering unwanted software and malware from user-initiated web traffic. It provides visibility and control over web usage and enforces security policies.',
		markdown: '#todo',
		related: []
	},
	// firewall-as-a-service
	{
		slug: 'firewall-as-a-service',
		acronym: 'FWaaS',
		full_form: 'Firewall as a Service',
		description:
			'FWaaS is a cloud-based security service that provides firewall protection for networks and applications. It offers scalability, flexibility, and centralized management of firewall policies and configurations.',
		markdown: '#todo',
		related: []
	},
	// software-as-a-service
	{
		slug: 'software-as-a-service',
		acronym: 'SaaS',
		full_form: 'Software as a Service',
		description:
			'SaaS is a software distribution model in which applications are hosted by a service provider and made available to customers over the Internet. It allows users to access software applications without the need for installation or maintenance.',
		markdown: '#todo',
		related: []
	},
	// platform-as-a-service
	{
		slug: 'platform-as-a-service',
		acronym: 'PaaS',
		full_form: 'Platform as a Service',
		description:
			'PaaS is a cloud computing model that provides a platform allowing customers to develop, run, and manage applications without the complexity of building and maintaining the infrastructure. It includes tools and services for application development.',
		markdown: '#todo',
		related: []
	},
	// infrastructure-as-a-service
	{
		slug: 'infrastructure-as-a-service',
		acronym: 'IaaS',
		full_form: 'Infrastructure as a Service',
		description:
			'IaaS is a cloud computing model that provides virtualized computing resources over the Internet. It allows users to rent IT infrastructure, such as servers and storage, on a pay-as-you-go basis.',
		markdown: '#todo',
		related: []
	},
	// function-as-a-service
	{
		slug: 'function-as-a-service',
		acronym: 'FaaS',
		full_form: 'Function as a Service',
		description:
			'FaaS is a cloud computing model that allows users to run individual functions or pieces of code in response to events without managing servers. It is a serverless computing model that enables rapid development and deployment of applications.',
		markdown: '#todo',
		related: []
	},
	// next-generation-firewall
	{
		slug: 'next-generation-firewall',
		acronym: 'NGFW',
		full_form: 'Next Generation Firewall',
		description:
			'NGFW is a network security device that goes beyond traditional firewalls by providing advanced features such as application awareness, intrusion prevention and deep packet inspection. It is designed to protect networks from sophisticated threats and attacks.',
		markdown: '#todo',
		related: []
	}
];

const getAcronymBySlug = (slug: String) => {
	const acronym = acronyms.find((acronym) => acronym.slug === slug);
	if (!acronym) {
		return null;
	}
	return acronym;
};

const getAllAcronyms = () => {
	let acronymsList = acronyms.map((acronyms) => {
		return {
			slug: acronyms.slug,
			acronym: acronyms.acronym,
			full_form: acronyms.full_form
		};
	});
	acronymsList.sort((a, b) => a.full_form.localeCompare(b.full_form));
	return acronymsList;
};

export { getAcronymBySlug, syncwithsearch, acronyms, getAllAcronyms };
export default acronyms;

async function syncwithsearch() {
	const axiosinstance = axios.create({
		baseURL: process.env.PUBLIC_MEILISEARCH_URL,
		headers: {
			'Content-Type': 'application/json',
			Authorization: 'Bearer ' + process.env.MEILISEARCH_KEY
		}
	});
	try {
		await axiosinstance.delete('/indexes/acronyms');
		await axiosinstance.post('/indexes', {
			uid: 'acronyms',
			primaryKey: 'slug'
		});
		await axiosinstance.post('/indexes/acronyms/documents?primaryKey=slug', acronyms);
		console.log('success');
	} catch (e) {
		console.log(e);
	}
}
